name: release

on:
  push:
    branches:
      - 'master'
      - '0.70'

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - run: ./gradlew release
        env:
          bintrayUser: ${{ secrets.bintrayUser }}
          bintrayApiKey: ${{ secrets.bintrayApiKey }}
          bintrayPassword: ${{ secrets.bintrayPassword }}